version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    network_mode: host
    env_file:
      - ../../../.env 
    environment:
      LOG_LEVEL: DEBUG
      WORKERS: "1"
      THREADS: "8"
      MODEL_DIR: /data/models
      BASIC_AUTH_USER: ""
      BASIC_AUTH_PASS: ""

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - ../../yulon_label_studio:/yulon_label_studio:ro